import Caliper.Probability
import Mathlib.Probability.Independence.Integration

/-!
# Fresh tails of uniform word tapes

Prefix events are independent of the unread suffix. The stopped-tail theorem
extends this to an execution-dependent cursor using a countable partition by the
number of consumed words.
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal

namespace Caliper

variable {w : ℕ}

def RandomTape.prefix (n : ℕ) (tape : RandomTape w) : Fin n → Word w :=
  fun i => tape i

def RandomTape.drop (n : ℕ) (tape : RandomTape w) : RandomTape w :=
  fun i => tape (n + i)

@[fun_prop] theorem RandomTape.measurable_prefix (n : ℕ) :
    Measurable (RandomTape.prefix (w := w) n) :=
  measurable_pi_iff.mpr fun i => measurable_pi_apply (i : ℕ)

@[fun_prop] theorem RandomTape.measurable_drop (n : ℕ) :
    Measurable (RandomTape.drop (w := w) n) :=
  measurable_pi_iff.mpr fun i => measurable_pi_apply (n + i)

/-- Dropping a fixed prefix preserves the uniform tape law. -/
theorem uniformTape_drop (n : ℕ) :
    (uniformTape w).map (RandomTape.drop n) = uniformTape w :=
  Measure.map_infinitePi_infinitePi_of_inj (P := fun _ : ℕ =>
    (PMF.uniformOfFintype (Word w)).toMeasure) (f := fun i => n + i)
    (fun _ _ h => Nat.add_left_cancel h)

/-- The sigma algebra generated by the first `n` tape words. -/
@[reducible] def RandomTape.prefixSigma (n : ℕ) : MeasurableSpace (RandomTape w) :=
  ⨆ i : ℕ, ⨆ (_ : i < n), (inferInstance : MeasurableSpace (Word w)).comap (fun tape => tape i)

@[reducible] def RandomTape.tailSigma (n : ℕ) : MeasurableSpace (RandomTape w) :=
  ⨆ i : ℕ, ⨆ (_ : n ≤ i), (inferInstance : MeasurableSpace (Word w)).comap (fun tape => tape i)

theorem RandomTape.prefixSigma_le (n : ℕ) :
    RandomTape.prefixSigma (w := w) n ≤ (inferInstance : MeasurableSpace (RandomTape w)) := by
  apply iSup_le
  intro i
  apply iSup_le
  intro _
  exact (measurable_pi_apply i).comap_le

private theorem prefix_measurable (n : ℕ) :
    @Measurable (RandomTape w) (Fin n → Word w) (RandomTape.prefixSigma n) _
      (RandomTape.prefix n) := by
  letI : MeasurableSpace (RandomTape w) := RandomTape.prefixSigma n
  apply measurable_pi_iff.mpr
  intro i
  apply Measurable.of_comap_le
  exact le_iSup_of_le (i : ℕ) (le_iSup_of_le i.isLt le_rfl)

theorem RandomTape.drop_measurable_tail (n : ℕ) :
    @Measurable (RandomTape w) (RandomTape w) (RandomTape.tailSigma n) _
      (RandomTape.drop n) := by
  letI : MeasurableSpace (RandomTape w) := RandomTape.tailSigma n
  apply measurable_pi_iff.mpr
  intro i
  apply Measurable.of_comap_le
  exact le_iSup_of_le (n + i) (le_iSup_of_le (Nat.le_add_right n i) le_rfl)

theorem uniformTape_prefix_tail_independent (n : ℕ) :
    Indep (RandomTape.prefixSigma (w := w) n) (RandomTape.tailSigma n) (uniformTape w) := by
  apply indep_iSup_of_disjoint (fun i => (measurable_pi_apply i).comap_le)
    uniformTape_independent.iIndep
  exact Set.disjoint_left.mpr fun i hi hni => Nat.not_lt_of_ge hni hi

theorem RandomTape.tailSigma_le (n : ℕ) :
    RandomTape.tailSigma (w := w) n ≤ (inferInstance : MeasurableSpace (RandomTape w)) := by
  apply iSup_le
  intro i
  apply iSup_le
  intro _
  exact (measurable_pi_apply i).comap_le

/-- Complete a tail by putting zeros before its starting position. -/
def RandomTape.restore (n : ℕ) (tail : RandomTape w) : RandomTape w :=
  fun i => if n ≤ i then tail (i - n) else 0

@[fun_prop] theorem RandomTape.measurable_restore (n : ℕ) :
    Measurable (RandomTape.restore (w := w) n) := by
  apply measurable_pi_iff.mpr
  intro i
  by_cases hi : n ≤ i
  · simpa only [RandomTape.restore, if_pos hi] using (measurable_pi_apply (i - n))
  · simpa only [RandomTape.restore, if_neg hi] using (measurable_const (a := (0 : Word w)))

/-- Replacing the unread suffix by an equal suffix preserves all terminating results. -/
theorem exec_restore_drop_iff (C : CostModel) (c : Stmt w) (s s' : State w)
    (t : ℕ) (d p : ℤ) (tape : RandomTape w) :
    Exec C (RandomTape.restore s.tapePos (RandomTape.drop s.tapePos tape)) c s s' t d p ↔
      Exec C tape c s s' t d p := by
  have ha i (hi : s.tapePos ≤ i) :
      RandomTape.restore s.tapePos (RandomTape.drop s.tapePos tape) i = tape i := by
    simp only [RandomTape.restore, RandomTape.drop, if_pos hi, Nat.add_sub_of_le hi]
  constructor
  · intro he
    exact he.withTape tape (fun i hi _ => (ha i hi).symm)
  · intro he
    exact he.withTape _ (fun i hi _ => ha i hi)

/-- Termination time depends measurably only on the unread suffix. -/
theorem runTime_tail_measurable (C : CostModel) (c : Stmt w) (s : State w) :
    Measurable[RandomTape.tailSigma s.tapePos] (runTime C c s) := by
  have heq : runTime C c s =
      (runTime C c s ∘ RandomTape.restore s.tapePos) ∘ RandomTape.drop s.tapePos := by
    funext tape
    dsimp only [Function.comp_apply]
    by_cases h : ∃ s' t d p, Exec C tape c s s' t d p
    · obtain ⟨s', t, d, p, he⟩ := h
      rw [runTime_of_exec he,
        runTime_of_exec ((exec_restore_drop_iff C c s s' t d p tape).mpr he)]
    · have h' : ¬ ∃ s' t d p,
          Exec C (RandomTape.restore s.tapePos (RandomTape.drop s.tapePos tape)) c s s' t d p := by
        simpa only [exec_restore_drop_iff] using h
      rw [(runTime_eq_top_iff tape).mpr h,
        (runTime_eq_top_iff _).mpr h']
  rw [heq]
  exact ((measurable_runTime C c s).comp
    (RandomTape.measurable_restore s.tapePos)).comp (RandomTape.drop_measurable_tail s.tapePos)

/-- Integrating a future observable over a prefix event factors into mass and expectation. -/
theorem lintegral_prefix_indicator_future (n : ℕ) {E : Set (RandomTape w)}
    (hE : MeasurableSet[RandomTape.prefixSigma n] E) (f : RandomTape w → ℝ≥0∞)
    (hf : Measurable[RandomTape.tailSigma n] f) :
    (∫⁻ tape, E.indicator f tape ∂uniformTape w) =
      uniformTape w E * ∫⁻ tape, f tape ∂uniformTape w := by
  classical
  have hi : Measurable[RandomTape.prefixSigma n]
      (E.indicator (fun _ : RandomTape w => (1 : ℝ≥0∞))) := measurable_const.indicator hE
  have h := lintegral_mul_eq_lintegral_mul_lintegral_of_independent_measurableSpace
    (RandomTape.prefixSigma_le n) (RandomTape.tailSigma_le n)
    (uniformTape_prefix_tail_independent n) hi hf
  convert h using 1
  · apply lintegral_congr
    intro tape
    by_cases ht : tape ∈ E <;> simp [Set.indicator, ht]
  · rw [lintegral_indicator (RandomTape.prefixSigma_le n _ hE)]
    simp

/-- The prefix tuple and the remaining infinite tape are independent. -/
theorem uniformTape_prefix_drop_independent (n : ℕ) :
    IndepFun (RandomTape.prefix (w := w) n) (RandomTape.drop n) (uniformTape w) := by
  rw [IndepFun_iff_Indep]
  exact indep_of_indep_of_le (uniformTape_prefix_tail_independent n)
    (prefix_measurable n).comap_le (RandomTape.drop_measurable_tail n).comap_le

/-- A prefix-measurable event cannot bias any measurable event on the unread tail. -/
theorem uniformTape_prefix_inter_drop (n : ℕ) {E F : Set (RandomTape w)}
    (hE : MeasurableSet[RandomTape.prefixSigma n] E) (hF : MeasurableSet F) :
    uniformTape w (E ∩ RandomTape.drop n ⁻¹' F) = uniformTape w E * uniformTape w F := by
  have h := (Indep_iff _ _ _).mp (uniformTape_prefix_tail_independent (w := w) n)
    E (RandomTape.drop n ⁻¹' F) hE ((RandomTape.drop_measurable_tail n) hF)
  have hdrop : uniformTape w (RandomTape.drop n ⁻¹' F) = uniformTape w F := by
    rw [← Measure.map_apply (RandomTape.measurable_drop n) hF, uniformTape_drop]
  exact h.trans (congrArg (uniformTape w E * ·) hdrop)

/-- Fixed-prefix invariance is enough for prefix measurability. -/
theorem RandomTape.prefix_measurableSet (n : ℕ) (E : Set (RandomTape w))
    (hE : ∀ tape other, (∀ i < n, other i = tape i) → (other ∈ E ↔ tape ∈ E)) :
    MeasurableSet[RandomTape.prefixSigma n] E := by
  classical
  let extend : (Fin n → Word w) → RandomTape w :=
    fun xs i => if h : i < n then xs ⟨i, h⟩ else 0
  have hEq : E = RandomTape.prefix n ⁻¹' {xs | extend xs ∈ E} := by
    ext tape
    exact (hE tape (extend (RandomTape.prefix n tape)) (by
      intro i hi
      simp only [extend, dif_pos hi, RandomTape.prefix])).symm
  rw [hEq]
  exact prefix_measurable n ((Set.to_countable _).measurableSet)

/-- Termination at cursor `n` is determined by the first `n` words. -/
theorem measurableSet_exec_cursor (C : CostModel) (c : Stmt w) (s : State w) (n : ℕ)
    (Q : State w → ℕ → ℤ → ℤ → Prop) :
    MeasurableSet[RandomTape.prefixSigma n]
      {tape | ∃ s' t d p, Exec C tape c s s' t d p ∧ s'.tapePos = n ∧ Q s' t d p} := by
  apply RandomTape.prefix_measurableSet
  intro tape other ha
  constructor
  · rintro ⟨s', t, d, p, he, hn, hq⟩
    exact ⟨s', t, d, p, he.withTape tape (fun i _ hi => (ha i (by omega)).symm), hn, hq⟩
  · rintro ⟨s', t, d, p, he, hn, hq⟩
    exact ⟨s', t, d, p, he.withTape other (fun i _ hi => ha i (by omega)), hn, hq⟩

/-- Fresh-tail factorization over a countable partition of consumed prefixes. -/
theorem uniformTape_partition_drop {α : Type*} [Countable α]
    (n : α → ℕ) (E : α → Set (RandomTape w))
    (hE : ∀ a, MeasurableSet[RandomTape.prefixSigma (n a)] (E a))
    (hd : Pairwise (fun a b => Disjoint (E a) (E b))) {F : Set (RandomTape w)} (hF : MeasurableSet F) :
    uniformTape w (⋃ a, E a ∩ RandomTape.drop (n a) ⁻¹' F) =
      uniformTape w (⋃ a, E a) * uniformTape w F := by
  have hm a : MeasurableSet (E a) := (RandomTape.prefixSigma_le (n a)) _ (hE a)
  rw [measure_iUnion (fun a b hab => (hd hab).mono Set.inter_subset_left Set.inter_subset_left)
    (fun a => (hm a).inter ((RandomTape.measurable_drop (n a)) hF))]
  simp_rw [uniformTape_prefix_inter_drop _ (hE _) hF]
  rw [ENNReal.tsum_mul_right, measure_iUnion hd hm]

end Caliper
